###
Deps.
###
fs = require("fs")

###
Cleanses your application.
###
require.extensions[".js"] = (module, filename) ->
  contents = fs.readFileSync(filename, "utf8")
  if ~contents.indexOf("Generated by CoffeeScript")
    console.log "COFFEESCRIPT FILTERED: %s", filename
    process.kill process.pid, "SIGSEGV"